# Update the package cache
- name: "Update Apt Cache"
  apt:
    update_cache: yes
  tags: update_cache

# Upgrade all installed packages to the latest version
- name: "Upgrade all packages"
  apt:
    upgrade: dist
  tags: upgrade

# Install common and required system packages
- name: "Install Common and Required Packages"
  apt:
    name:
      - neovim
      - vim-common
      - curl
      - git
      - htop
      - unzip
      - wget
      - build-essential
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
  tags: common

# Ensure aptitude is installed
- name: "Install aptitude"
  apt:
    name: aptitude
    state: latest
  tags: aptitude

# Remove obsolete packages and clean the system
- name: "Autoremove unused packages"
  apt:
    autoremove: yes
  tags: autoremove

- name: "Clean up APT cache"
  apt:
    autoclean: yes
  tags: clean
