---
- name: Install Docker dependencies (Raspberry Pi specific)
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest

- name: Add Docker GPG key
  command: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  copy:
    content: |
      deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable
    dest: /etc/apt/sources.list.d/docker.list
  notify: Update apt cache

- name: Update apt cache
  apt:
    update_cache: true

- name: Install Docker
  apt:
    name: docker-ce
    state: latest

- name: Install Docker Python module
  pip:
    name: docker

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create default containers
  community.docker.docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    state: present
  with_sequence: count={{ container_count }}

